name: build-static-files

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Read package version
        uses: nyaa8/package-version@v1
        with:
          path: "packages/gephi-lite/package.json"

      - name: Build
        run: npm run build
        env:
          BASE_URL: ./

      - name: Prepare website directory
        run: |
          mkdir -p website
          cp -rf packages/gephi-lite/build/* website/

      - name: Remove source maps
        run: |
          find website -name "*.map" -type f -delete

      - name: Create tar archive
        run: |
          tar -czf gephi-lite-v${{ env.PACKAGE_VERSION }}.tar.gz website

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gephi-lite-v${{ env.PACKAGE_VERSION }}
          path: gephi-lite-v${{ env.PACKAGE_VERSION }}.tar.gz
          if-no-files-found: error

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: Gephi Lite v${{ env.PACKAGE_VERSION }}
          generate_release_notes: true
          files: |
            gephi-lite-v${{ env.PACKAGE_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
